### ISSUE TITLE
Using ts2fable to generate types

### ISSUE THREAD

**Issue by joshuapassos** [fable-compiler/fable-node#28]
It's possible or maybe a good option, to use ts2fable to generate partial types from @types/node?

**Comment by MangelMaxime** [comment]
Hello,

I think that like with most bindings, we use ts2fable to do 80-90% of the work and tweaks it manually.

What action do you expect us to take from issue? I am not sure what the question is here sorry.

**Comment by joshuapassos** [comment]
It was only question. Thank you!
