### ISSUE TITLE
missing binding for TextEncoder

### ISSUE THREAD

**Issue by joprice** [fable-compiler/fable-node#30]
Node provides [TextEncoder class](https://nodejs.org/api/util.html#class-utiltextencoder) that implements the same [interface as the browser](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) api in a "util" namespace `util.TextEncoder` as well as a global object.

**Comment by MangelMaxime** [comment]
Hello,

I added `util.TextEncoder` in version 1.3.0

I only added this one to avoid conflict between types. Fable.Node will one day be replaced with a generated one by Glutinum which should be more complete.

Usage:

```fs
open Node.Util

let encoder = Exports.TextEncoder()

open type Exports

let encoder2 = TextEncoder()
```
