### ISSUE TITLE
URLSearchParams missing object and iterable overrides

### ISSUE THREAD

**Issue by joprice** [fable-compiler/fable-node#32]
URLSearchParams allows creating an instance from an object or an iterable of key value pairs:  https://nodejs.org/api/url.html#new-urlsearchparamsobj. The current implementation only supports a string https://github.com/fable-compiler/fable-node/blob/939b4e012473ddda3bc97d92814db95a3fd3ebc6/src/Url.fs#L22-L25.

**Comment by MangelMaxime** [comment]
I am unsure what Fable use to represent Iterable, should we make `iterable` to `seq`?

**Comment by MangelMaxime** [comment]
Thanks for the report fixed in version 1.4.0
