### ISSUE TITLE
NetworkFamily has incorrect casing

### ISSUE THREAD

**Issue by joprice** [fable-compiler/fable-node#33]
The StringEnum on IPv6 results in the first letter being lowercase `iPv6`, whereas the casing should be `IPv6`. Switching to `[<StringEnum(CaseRules.None)>]` should fix it. I was going to make the change and wanted to write a test for it, but I'm hitting some errors when trying to run tests:

```
Couldn't remove project reference Fable.Node from dll references
ERROR: The specified file name or path is too long, or a component of the specified path is too long.
```

**Comment by MangelMaxime** [comment]
> The specified file name or path is too long, or a component of the specified path is too long.

It has been a long since I last saw this issue. I believe this is related to Windows path system.

**Comment by joprice** [comment]
I'm on a mac, but I use Nix. Perhaps it's something being referenced from the nix store. I'll try to build it again at some point and see if I can isolate it.
