### ISSUE TITLE
latest release requires FSharp.Core 9

### ISSUE THREAD

**Issue by joprice** [fable-compiler/fable-node#34]
When attempting to use version 1.4.0, I get the following error from paket:

```
     Conflict detected:
      - Dependencies file requested package FSharp.Core: >= 0
      - Fable.Node 1.4.0 requested package FSharp.Core: >= 9.0.100-beta.24406.3 (beta)
```

Checking on nuget, it seems that the release depends on `FSharp.Core (>= 9.0.100-beta.24406.3)` https://www.nuget.org/packages/Fable.Node/1.4.0#dependencies-body-tab whereas the previous depended on `FSharp.Core (>= 8.0.400-beta.24229.4)`. The release prior to that depended on 5.0, so I assume it has been picking up local versions when releasing. Maybe the package should pin the version to the minimum supported version to avoid unintentionally raising the lower bound during release?

**Comment by MangelMaxime** [comment]
Thanks for seeing this issue.

I made a new release and forced to keep track of FSharp.Core in the fsproj so now it should be independent of the .SDK version used to pack the package.
