### ISSUE TITLE
LTS & legacy Support

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-node#6]
Hi,
since we're moving out of the "tinkering with Fable and Node.js" side with these brand new bindings, what do we want to support? 

I started revamping APIs to support LTS and maybe new experimental features. But do we need to support legacy, pre 10.x as well? (Node.js 6? Nodejs 8?).

**Comment by MangelMaxime** [comment]
We can just support LTS I think. From what I know in general major version of Node.js is backwards compatible so people will "just" have access to more things than what they can really use.

Could be interesting to look at how it's done for the `d.ts` files. If they support per-version or one global.

**Comment by whitetigle** [comment]
Well while it's backward compatible, the real question was more do we start with current implementation as  of today? But you answered my question.

In the doc, things are [clearly specified](https://nodejs.org/docs/latest/api/url.html#url_legacy_url_api) regarding legacy code.

**Comment by alfonsogarciacaro** [comment]
There're a few APIs that are deprecated but I think are still commonly used like [file.exists](https://nodejs.org/docs/latest/api/fs.html#fs_fs_exists_path_callback).

**Comment by MangelMaxime** [comment]
Well we can always put `Obselete` attribute on top of the API saying that to use API X if people are using a later version of node than X.Y.Z. But it can be hard to maintain

**Comment by whitetigle** [comment]
> There're a few APIs that are deprecated but I think are still commonly used like file.exists.

Ok let's ask. 😉 But anyway it won't cost much to add Obsolete as required and then we'll always issues if people need something missing.

**Comment by whitetigle** [comment]
Done! 😀 

![image](https://user-images.githubusercontent.com/883207/56134291-9a494a80-5f8e-11e9-9bbd-51e51669d7c3.png)
