### ISSUE TITLE
Console?

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-node#7]
No [Console ](https://nodejs.org/docs/latest/api/console.html) types found so far in the API. Is it something that was just missing or left out on purpose?

**Comment by nojaf** [comment]
Are these not exactly the same as https://github.com/fable-compiler/Fable/blob/c12678d4cbff2fd7e7bc29dca5ae83ab868bffab/src/Fable.Core/Fable.Core.JS.fs#L267?

**Comment by alfonsogarciacaro** [comment]
Yes, I removed them from here and from the browser to encourage people to use `JS.console` which is already include in Fable.Core.

**Comment by whitetigle** [comment]
So should I link `Api.console` to `Js.console` in order to mimic the Node API (console is in Globals)?

**Comment by alfonsogarciacaro** [comment]
For now, I would just remove `Api.console`, users can call `JS.console` instead.

**Comment by whitetigle** [comment]
ok
